### ISSUE TITLE
Internal Error running simple SQL

### ISSUE THREAD

**Issue by peterpk** [IBM/db2forzosdeveloperextension-about#33]
[client_2021-02-23T183933.log](https://github.com/IBM/db2forzosdeveloperextension-about/files/6031204/client_2021-02-23T183933.log)
I set up a connection to a Db2/z subsystem running Db2 12 Function level 100 (old "Compatibility Mode").  It connects ok, but when I try to run a simple query (highlight SQL and choose "Run selected SQL" from popup menu) I get an "Internal Error" message.  No other information is immediately apparent.

In extension logs (attached) I found this:

```
2021-02-23T13:40:01.758-0500 DEBUG: ConnectionService:getConnection: Getting the connection usibmvrdd1h.ssiplex.pok.ibm.com/USIBMVRDD1H.
2021-02-23T13:40:01.758-0500 INFO : Version V11 detected.
```

It finally ends with:

`java.lang.ClassCastException: com.ibm.db.parsers.sql.db2.zos.parser.v11.DB2ZOSv11Parser cannot be cast to com.ibm.db.parsers.sql.db2.zos.parser.v12.DB2ZOSv12Parser`

Is it getting confused by the Compatibility Mode?

**Comment by danluksetich** [comment]
I am getting a similar error for a V12R1M100 level subsystem
SEVERE: Internal error: java.lang.ClassCastException: com.ibm.db.parsers.sql.db2.zos.parser.v11.DB2ZOSv11Parser incompatible with com.ibm.db.parsers.sql.db2.zos.parser.v12.DB2ZOSv12Parser

**Comment by realkendrickren** [comment]
@peterpk @danluksetich thanks a lot for reporting this issue. We are looking into the issue immediately...

**Comment by realkendrickren** [comment]
@peterpk @danluksetich @scotdb we just published a hotfix v1.1.1 to fix the issue. 

Can you please upgrade the extension in VSCode and give a try? Let me know if there is any issue. 

Thanks.

**Comment by danluksetich** [comment]
it works!

**Comment by realkendrickren** [comment]
@danluksetich thanks for the confirmation, Dan!

**Comment by scotdb** [comment]
As discussed, while the Extension now doesn't fail I'm still having an
issue with regard to deployment of SP code related to WLM environment
specification.

I'll produce a trace on Monday and share it with you.

Phil
